name: Prettier Auto Format and Commit

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  format:
    runs-on: ubuntu-latest

    # 메인 레포에서만 실행
    if: github.repository == 'SWPP-2025SPRING/team-project-for-2025-spring-swpp-team-02'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Prettier
        run: npm install -g prettier

      - name: Run Prettier on Markdown and JSON
        run: prettier --write "**/*.{md,json}"

      - name: Commit changes if needed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if ! git diff --cached --quiet; then
            git commit -m "chore: auto-format markdown and json"
            git push
          fi
